name: sunny
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 5.0.1
  flutter_svg: 2.0.2
  geocoding: 2.0.5
  geolocator: 9.0.2
  intl: 0.18.0
  just_audio: 0.9.31
  loading: 1.0.2
  url_launcher: 6.1.10

dev_dependencies:
  flutter_launcher_icons: 0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#414288'
  adaptive_icon_foreground: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/conditions/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
