import 'package:flutter/painting.dart';

import '../colors.dart';
import '../strings.dart';

String getCondition(weatherCondition) {
  switch (weatherCondition) {
    case 'clearsky_day':
      return clearsky_day;
    case 'clearsky_night':
      return clearsky_night;
    case 'fair_day':
      return fair_day;
    case 'fair_night':
      return fair_night;
    case 'heavyrainshowers_day':
      return heavyrainshowers_day;
    case 'heavyrainshowers_night':
      return heavyrainshowers_night;
    case 'heavyrainshowersandthunder_day':
      return heavyrainshowersandthunder_day;
    case 'heavyrainshowersandthunder_night':
      return heavyrainshowersandthunder_night;
    case 'heavysleetshowers_day':
      return heavysleetshowers_day;
    case 'heavysleetshowers_night':
      return heavysleetshowers_night;
    case 'heavysleetshowersandthunder_day':
      return heavysleetshowersandthunder_day;
    case 'heavysleetshowersandthunder_night':
      return heavysleetshowersandthunder_night;
    case 'heavysnowshowers_day':
      return heavysnowshowers_day;
    case 'heavysnowshowers_night':
      return heavysnowshowers_night;
    case 'heavysnowshowersandthunder_day':
      return heavysnowshowersandthunder_day;
    case 'heavysnowshowersandthunder_night':
      return heavysnowshowersandthunder_night;
    case 'lightrainshowers_day':
      return lightrainshowers_day;
    case 'lightrainshowers_night':
      return lightrainshowers_night;
    case 'lightrainshowersandthunder_day':
      return lightrainshowersandthunder_day;
    case 'lightrainshowersandthunder_night':
      return lightrainshowersandthunder_night;
    case 'lightsleetshowers_day':
      return lightsleetshowers_day;
    case 'lightsleetshowers_night':
      return lightsleetshowers_night;
    case 'lightsnowshowers_day':
      return lightsnowshowers_day;
    case 'lightsnowshowers_night':
      return lightsnowshowers_night;
    case 'lightssleetshowersandthunder_day':
      return lightssleetshowersandthunder_day;
    case 'lightssleetshowersandthunder_night':
      return lightssleetshowersandthunder_night;
    case 'lightssnowshowersandthunder_day':
      return lightssnowshowersandthunder_day;
    case 'lightssnowshowersandthunder_night':
      return lightssnowshowersandthunder_night;
    case 'partlycloudy_day':
      return partlycloudy_day;
    case 'partlycloudy_night':
      return partlycloudy_night;
    case 'rainshowers_day':
      return rainshowers_day;
    case 'rainshowers_night':
      return rainshowers_night;
    case 'rainshowersandthunder_day':
      return rainshowersandthunder_day;
    case 'rainshowersandthunder_night':
      return rainshowersandthunder_night;
    case 'sleetshowers_day':
      return sleetshowers_day;
    case 'sleetshowers_night':
      return sleetshowers_night;
    case 'sleetshowersandthunder_day':
      return sleetshowersandthunder_day;
    case 'sleetshowersandthunder_night':
      return sleetshowersandthunder_night;
    case 'snowshowers_day':
      return snowshowers_day;
    case 'snowshowers_night':
      return snowshowers_night;
    case 'snowshowersandthunder_day':
      return snowshowersandthunder_day;
    case 'snowshowersandthunder_night':
      return snowshowersandthunder_night;
    case 'cloudy':
      return cloudy;
    case 'fog':
      return fog;
    case 'heavyrain':
      return heavyrain;
    case 'heavyrainandthunder':
      return heavyrainandthunder;
    case 'heavysleet':
      return heavysleet;
    case 'heavysleetandthunder':
      return heavysleetandthunder;
    case 'heavysnow':
      return heavysnow;
    case 'heavysnowandthunder':
      return heavysnowandthunder;
    case 'lightrain':
      return lightrain;
    case 'lightrainandthunder':
      return lightrainandthunder;
    case 'lightsleet':
      return lightsleet;
    case 'lightsleetandthunder':
      return lightsleetandthunder;
    case 'lightsnow':
      return lightsnow;
    case 'lightsnowandthunder':
      return lightsnowandthunder;
    case 'rain':
      return rain;
    case 'rainandthunder':
      return rainandthunder;
    case 'sleet':
      return sleet;
    case 'sleetandthunder':
      return sleetandthunder;
    case 'snow':
      return snow;
    case 'snowandthunder':
      return snowandthunder;

    default:
      return noCondition;
  }
}

List<Color> getColors(condition) {
  switch (condition) {
    case 'clearsky_day':
      return dayColors;
    case 'clearsky_night':
      return nightColors;
    case 'fair_day':
    case 'fair_night':
      return fairColors;
    case 'cloudy':
    case 'partlycloudy_day':
    case 'partlycloudy_night':
      return cloudyColors;
    case 'fog':
      return fogColors;
    case 'heavyrain':
    case 'heavyrainandthunder':
    case 'heavyrainshowers_day':
    case 'heavyrainshowers_night':
    case 'heavyrainshowersandthunder_day':
    case 'heavyrainshowersandthunder_night':
    case 'lightrain':
    case 'lightrainandthunder':
    case 'lightrainshowers_day':
    case 'lightrainshowers_night':
    case 'lightrainshowersandthunder_day':
    case 'lightrainshowersandthunder_night':
    case 'rain':
    case 'rainandthunder':
    case 'rainshowers_day':
    case 'rainshowers_night':
    case 'rainshowersandthunder_day':
    case 'rainshowersandthunder_night':
      return rainColors;
    case 'heavysleet':
    case 'heavysleetandthunder':
    case 'heavysleetshowers_day':
    case 'heavysleetshowers_night':
    case 'heavysleetshowersandthunder_day':
    case 'heavysleetshowersandthunder_night':
    case 'lightsleet':
    case 'lightsleetandthunder':
    case 'lightsleetshowers_day':
    case 'lightsleetshowers_night':
    case 'lightssleetshowersandthunder_day':
    case 'lightssleetshowersandthunder_night':
    case 'sleet':
    case 'sleetandthunder':
    case 'sleetshowers_day':
    case 'sleetshowers_night':
    case 'sleetshowersandthunder_day':
    case 'sleetshowersandthunder_night':
      return sleetColors;
    case 'heavysnow':
    case 'heavysnowandthunder':
    case 'heavysnowshowers_day':
    case 'heavysnowshowers_night':
    case 'heavysnowshowersandthunder_day':
    case 'heavysnowshowersandthunder_night':
    case 'lightsnow':
    case 'lightsnowandthunder':
    case 'lightsnowshowers_day':
    case 'lightsnowshowers_night':
    case 'lightssnowshowersandthunder_day':
    case 'lightssnowshowersandthunder_night':
    case 'snow':
    case 'snowandthunder':
    case 'snowshowers_day':
    case 'snowshowers_night':
    case 'snowshowersandthunder_day':
    case 'snowshowersandthunder_night':
      return snowColors;

    default:
      return primaryColors;
  }
}
